services:
  - type: web
    name: python-web-crawler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: FLASK_ENV
        value: production